### ISSUE TITLE
PS1 2352 image EDC/ECC recalculator

### ISSUE THREAD

**Issue by jerkstore369** [pyriell/gs2-bugfixes#4]
Hi, I just have a question. If I'm patching a bin file does the EDC/ECC need to be recalculated? Because some PS1 hacks don't work on hardware/accurate emulators otherwise (they'll have errors) and I know this disc had an audio track on it. Thanks.

re: http://www.romhacking.net/utilities/1264/

I guess it won't hurt to just do it?..

**Comment by pyriell** [comment]
I've played the patch on 3-4 different PC emulators, POPS on a PSP, and on real, modded hardware before.  It really shouldn't be an issue.

I think that utility is mostly for PPF-style patches that write changes to a disc image, treating it only as a large file.  It would be necessary there if the patch creator didn't rebuild the patched disc to generate new ECC segments prior to building the PPF they released.  The lua-interface/cd-util that does the low-level disc work for this patch copies all the data files from the original, including audio, applies patches to the files individually, and then rebuilds a new disc image from scratch.  New error correction codes should be calculated as each sector is written to the new image.

**Comment by jerkstore369** [comment]
Thanks. I guess that's what happened. The patch creator didn't rebuild the patched disc I guess. Specifically, the Symphony of the Night Hardtype hack. For a while it never worked for me in OpenEmu (mednafen), and I read that some ppf PS1 patches don't work in accurate emulators. I was browsing the megaman x6 tweaks page and saw that his patch uses some tool to recalculate the ECC and I tried that In hardtype and now it works with no errors. Originally it had bugs like killing a gold medusa head would freeze the game. But it worked perfectly in epsxe for whatever reason. Anyways, thanks.
