### ISSUE TITLE
4 Lamb for Cooking

### ISSUE THREAD

**Issue by Sdub-12** [pyriell/gs2-bugfixes#7]
So, I played the patch all the way through and everything worked great. But for some reason even after getting all the lambs including the one chest in the kobold forest. I still only have 3 Lamb meat listen. So i cant make the one Ghenkis Khan Dish.

**Comment by Sdub-12** [comment]
Turned out i just had to keep resetting the shop for saraj town.

**Comment by pyriell** [comment]
Oh, you mean you didn't have the recipe?

**Comment by Sdub-12** [comment]
No i did actually!, It just took an extremely long time for me to get the 4th Lamb to show up in the rare finds of Sajah. Sorry about that

**Comment by pyriell** [comment]
Oh, it's been a while.  I didn't realize that one of them was a rare find.

**Comment by Sdub-12** [comment]
There is! its in the very last town you can find. at the end of the game. there arent even any hints that it exists. I honestly havent gotten the fourth lamb yet after resetting the game tons of times. so im getting a little worried. As far as the lambs go its.
\
1. is already brought with yuzu
2. Buy in forest village
3. Capture in Kobold village.
4. Buy in Sajah from rare items

So far i have all three, including the one fix for number 3. 
Number 4 has not shown up yet.
